/* AUTO-GENERATED FILE. DO NOT MODIFY.
 * This class was automatically generated by the
 * static binding generator from the resources it found.
 * Please do not modify by hand.
 */
package com.ciriscr.geotest.location;

@com.tns.JavaScriptImplementation(javaScriptFile = "./bundle.js")
public class BackgroundService extends android.app.Service implements com.tns.NativeScriptHashCodeProvider {
	public BackgroundService(){
		super();
		com.tns.Runtime.initInstance(this);
	}

	public int onStartCommand(android.content.Intent param_0, int param_1, int param_2)  {
		java.lang.Object[] args = new java.lang.Object[3];
		args[0] = param_0;
		args[1] = param_1;
		args[2] = param_2;
		return (int)com.tns.Runtime.callJSMethod(this, "onStartCommand", int.class, args);
	}

	public void onCreate()  {
		java.lang.Object[] args = null;
		com.tns.Runtime.callJSMethod(this, "onCreate", void.class, args);
	}

	public android.os.IBinder onBind(android.content.Intent param_0)  {
		java.lang.Object[] args = new java.lang.Object[1];
		args[0] = param_0;
		return (android.os.IBinder)com.tns.Runtime.callJSMethod(this, "onBind", android.os.IBinder.class, args);
	}

	public boolean onUnbind(android.content.Intent param_0)  {
		java.lang.Object[] args = new java.lang.Object[1];
		args[0] = param_0;
		return (boolean)com.tns.Runtime.callJSMethod(this, "onUnbind", boolean.class, args);
	}

	public void onDestroy()  {
		java.lang.Object[] args = null;
		com.tns.Runtime.callJSMethod(this, "onDestroy", void.class, args);
	}

	public boolean equals__super(java.lang.Object other) {
		return super.equals(other);
	}

	public int hashCode__super() {
		return super.hashCode();
	}

}
